### ISSUE TITLE
Spotbugs not found. 

### ISSUE THREAD

**Issue by keshavashta** [Samagra-Development/mobile-package-issues#1]
* Create New Project 
* Import custom work manager from this https://github.com/Samagra-Development/mobile-forms
* Added custom work manager in dependencies 
* Importing collect_app, then its throwing an error ERROR: Plugin with id 'com.github.spotbugs'

**Comment by keshavashta** [comment]
Steps to reproduce:
* Create New Project 
* Import custom work manager from this https://github.com/Samagra-Development/mobile-forms
* Added custom work manager in dependencies 
* Importing collect_app, then its throwing an error ERROR: Plugin with id 'com.github.spotbugs'

**Comment by ChakshuGautam** [comment]
Moved this [here](https://github.com/Samagra-Development/mobile-forms/issues/1) and hence closing this.
